repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
      - id: forbid-crlf
  - repo: local
    hooks:
      - id: make_lint
        name: Run Linters
        language: system
        entry: make lint
        files: '^(plugin|lua)/.*\.lua$'
        verbose: true
      - id: make_docs
        name: Generate Docs
        language: system
        entry: make documentation
        files: '^(plugin|lua)/.*\.lua$'
        verbose: true
